"""Test whether the model can find transmission that is really there.

Simulate an economy from the model at KNOWN parameters, hand the simulated
data to the estimator with the same priors, and see where the posterior lands.

Two settings:

  posterior  the real-data posterior means. Recovers the structure the real
             run reported, so a miss here says the real run's numbers are
             not what the model would return from its own world.
  strong     transmission well above the prior (b2 = 0.25, kappa = 3). If the
             posterior stays at the prior when the truth is this far away, a
             low real-data b2 is the prior talking, not the data.

THE SIMULATION IS FULLY ENDOGENOUS. The estimator treats the cash rate as data
in the transition, but here it is generated by the rule each quarter from the
simulated gap, inflation and wedge, and fed back into the IS curve and the
exchange rate. So the thermostat problem is present in the simulated data
exactly as the model says it is in the real data. Exogenous series (expected
inflation, the world rate, import prices) are the real ones.
"""

from collections.abc import Mapping

import arviz as az
import mgplot as mg
import numpy as np
import pandas as pd

from src.models.rstar_qpm.config import ModelConfig
from src.models.rstar_qpm.estimate import estimate, parameter_names, posterior_params
from src.models.rstar_qpm.neutral import short_run_neutral
from src.models.rstar_qpm.state_space import N_STATES, QGAP, QSTAR, YGAP, YGAP_1, YSTAR, G, W, prepare
from src.models.ystar.base import SamplerConfig
from src.paths import CHARTS

CHART_DIR = CHARTS / "RStarQPM_recovery"

# The strong-transmission truth, overriding the real-data posterior means.
STRONG = {"b2": 0.25, "kappa": 3.0}

# The parameters the test is about, printed first.
TRANSMISSION = ("b1", "b2", "b3", "kappa", "rho_q", "phi_pi", "phi_y", "rho_i")

# Quarters of simulated inflation before the sample, for the year-ended rate.
_PI_HISTORY = 3


def simulate_economy(
    frame: pd.DataFrame,
    p: Mapping[str, float],
    config: ModelConfig,
    rng: np.random.Generator,
) -> tuple[pd.DataFrame, np.ndarray]:
    """Return a simulated observation frame and the true states behind it."""
    n = len(frame)
    pie, rw, m4 = (frame[c].to_numpy(dtype=float) for c in ("pie", "rw", "m4"))
    pie_lag, rw_lag, m4_lag = (frame[c].to_numpy(dtype=float) for c in ("pie_lag", "rw_lag", "m4_lag"))
    exposure = frame["exposure"].to_numpy(dtype=float)
    prep = prepare(frame, config)

    s = prep.s0.copy()
    states = np.zeros((n, N_STATES))
    i_prev = float(frame["i_lag"].iloc[0])
    r_prev = float(frame["r_lag"].iloc[0])
    pi_prev = float(frame["pi_lag"].iloc[0])
    dsr_prev = float(frame["d_dsr_lag"].iloc[0])
    pi_hist = [pi_prev] * _PI_HISTORY
    out = {k: np.zeros(n) for k in ("y", "q", "pi", "pi4", "i", "r", "f", "d_dsr")}

    def shock(name: str) -> float:
        return p[name] * float(rng.standard_normal())

    for t in range(n):
        wedge = s[W] + shock("sigma_w")
        ygap = (p["b1"] * s[YGAP] - p["b2"] * (r_prev - rw_lag[t] - s[W])
                - p["b3"] * s[QGAP] - p["b4"] * dsr_prev + shock("sigma_ygap"))
        ystar = s[YSTAR] + s[G] / 4.0 + shock("sigma_ystar")
        growth = s[G] + shock("sigma_g")
        pi = (p["a1"] * pi_prev + (1 - p["a1"]) * pie[t] + p["a2"] * s[YGAP]
              + p["a3"] * (m4_lag[t] - pie_lag[t]) + shock("sigma_pi"))
        pi4 = float(np.mean([pi, *pi_hist[-_PI_HISTORY:]]))
        rate = (p["rho_i"] * i_prev + (1 - p["rho_i"]) * (rw[t] + wedge + pie[t]
                + p["phi_pi"] * (pi4 - config.target) + p["phi_y"] * ygap) + shock("sigma_i"))
        real = rate - pie[t]
        # Debt servicing follows the simulated cash rate, on the real debt stock.
        d_dsr = p["delta"] * exposure[t] * (rate - i_prev) + shock("sigma_d")
        qgap = p["rho_q"] * s[QGAP] + p["kappa"] * (real - rw[t] - wedge) + shock("sigma_qgap")
        qstar = s[QSTAR] + shock("sigma_qstar")

        new = np.zeros(N_STATES)
        new[[YSTAR, G, YGAP, YGAP_1, W, QSTAR, QGAP]] = [ystar, growth, ygap, s[YGAP], wedge, qstar, qgap]
        states[t] = new
        s = new
        out["y"][t], out["q"][t] = ystar + ygap, qstar + qgap
        out["pi"][t], out["pi4"][t], out["i"][t], out["r"][t] = pi, pi4, rate, real
        out["f"][t] = rw[t] + wedge + p["forward_bias"] + shock("sigma_f")
        out["d_dsr"][t] = d_dsr
        pi_hist.append(pi)
        i_prev, r_prev, pi_prev, dsr_prev = rate, real, pi, d_dsr

    sim = pd.DataFrame(out, index=frame.index)
    sim["pie"], sim["rw"], sim["m4"] = pie, rw, m4
    sim["pie_lag"], sim["rw_lag"], sim["m4_lag"] = pie_lag, rw_lag, m4_lag
    sim["exposure"] = exposure
    for name in ("pi", "i", "r", "d_dsr"):
        sim[f"{name}_lag"] = np.concatenate([[float(frame[f"{name}_lag"].iloc[0])], out[name][:-1]])
    sim["d_i"] = sim["i"] - sim["i_lag"]
    return sim, states


def _truths(real_means: dict[str, float]) -> dict[str, dict[str, float]]:
    return {"posterior": dict(real_means), "strong": {**real_means, **STRONG}}


def _report(label: str, truth: Mapping[str, float], trace_means: dict[str, float],
            trace_sds: dict[str, float], config: ModelConfig) -> pd.DataFrame:
    rows = {}
    for name in config.estimated_priors:
        prior_mean, _ = config.priors[name].moments()
        rows[name] = {"truth": truth[name], "prior mean": prior_mean,
                      "post mean": trace_means[name], "post sd": trace_sds[name],
                      "error (post sds)": (trace_means[name] - truth[name]) / trace_sds[name]}
    table = pd.DataFrame(rows).T
    order = [n for n in TRANSMISSION if n in table.index] + [n for n in table.index if n not in TRANSMISSION]
    table = table.loc[order]
    print(f"\n=== Recovery: {label} ===")
    print(table.round(3).to_string())
    return table


def run_recovery(
    real_trace: az.InferenceData,
    frame: pd.DataFrame,
    config: ModelConfig,
    sampler_config: SamplerConfig,
    seed: int = 7,
) -> dict[str, pd.DataFrame]:
    """Simulate at each truth, re-estimate, print the tables, chart the paths."""
    names = parameter_names(config.estimated_priors)
    real = posterior_params(real_trace, names, n_draws=10**9)  # every draw
    real_means = {name: float(np.mean([d[name] for d in real])) for name in names}
    real_means.update(config.fixed)

    mg.set_chart_dir(str(CHART_DIR))
    mg.clear_chart_dir()
    tables = {}
    for label, truth in _truths(real_means).items():
        rng = np.random.default_rng(seed)
        sim, true_states = simulate_economy(frame, truth, config, rng)
        trace, states = estimate(sim, config, sampler_config)
        draws = posterior_params(trace, names, n_draws=10**9)
        means = {n: float(np.mean([d[n] for d in draws])) for n in names}
        sds = {n: float(np.std([d[n] for d in draws])) for n in names}
        tables[label] = _report(label, truth, means, sds, config)

        prep = prepare(sim, config)
        true_srn, true_mult = short_run_neutral(true_states, truth, prep, config.horizon)
        est_srn = states["paths"]["srn"].median(axis=1)
        print(f"  multiplier B (latest quarter): truth {true_mult[-1]:.3f}, posterior median "
              f"{np.median(states['multiplier']):.3f}")
        print(f"  short-run neutral: corr(true, estimated) {np.corrcoef(true_srn, est_srn)[0, 1]:.3f}, "
              f"RMSE {np.sqrt(np.mean((true_srn - est_srn) ** 2)):.3f}")
        # The level test above passes on trend r* alone, which the forward pins
        # in truth and estimate alike. What is new in short-run neutral is its
        # deviation from trend r*, so that is scored separately.
        true_dev = true_srn - (sim["rw"].to_numpy() + true_states[:, W])
        est_dev = est_srn - states["paths"]["rstar"].median(axis=1)
        print(f"  short-run neutral less trend r*: corr(true, estimated) "
              f"{np.corrcoef(true_dev, est_dev)[0, 1]:.3f}, sd truth {np.std(true_dev):.3f}, "
              f"sd estimated {np.std(est_dev):.3f}")
        true_gap = pd.Series(true_states[:, YGAP], index=sim.index)
        print(f"  output gap: corr(true, estimated) "
              f"{np.corrcoef(true_gap, states['paths']['ygap'].median(axis=1))[0, 1]:.3f}")

        for key, truth_path, title, ylabel in (
            ("srn", pd.Series(true_srn, index=sim.index), "short-run neutral", "Per cent, real"),
            ("ygap", true_gap, "output gap", "Per cent of potential"),
        ):
            chart = pd.DataFrame({"Truth": truth_path, "Estimated (median)": states["paths"][key].median(axis=1)})
            mg.line_plot_finalise(
                chart, title=f"Recovery, {label}: {title}", ylabel=ylabel,
                width=[2.0, 1.5], y0=True,
                legend={"loc": "best", "fontsize": "x-small"},
                lfooter="Simulated economy. Truth from the model at known parameters. ",
                rfooter=f"b2 truth {truth['b2']:.3f}, kappa truth {truth['kappa']:.2f}",
                show=False,
            )
    return tables
